spring.application.name=agricole
spring.datasource.url=jdbc:postgresql://localhost:5432/federation_agricole
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
